name: clipper
description: Login screen made using clippers.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.0.0
  connectivity: ^3.0.3
  cupertino_icons: ^1.0.2
  fzregex: ^1.0.3
  google_fonts: ^2.0.0
  http: ^0.13.3
  provider: ^5.0.0
  shared_preferences: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/
